# Generated by Django 3.1.1 on 2020-09-27 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('address_1', models.CharField(max_length=1024)),
                ('address_2', models.CharField(blank=True, max_length=1024)),
                ('city', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=512)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.IntegerField()),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_family', to='families.family')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
