# Generated by Django 3.1.1 on 2020-09-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('address_1', models.CharField(max_length=1024)),
                ('address_2', models.CharField(blank=True, max_length=1024)),
                ('city', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=512)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
