# Generated by Django 3.1.1 on 2020-09-27 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_family', to='families.family'),
        ),
    ]
