version: '3'

services:
  django: &django
    build:
      context: ./
      dockerfile: ./compose/django/Dockerfile
    command: ./compose/django/start.sh
    env_file:
      - ./compose/local.env
    image: sherbet_django
    ports:
      - "8000:8000"
  postgres:
    env_file:
      - ./compose/local.env
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
