version: '3'

services:
  django: &django
    build:
      args:
        - DOCKER_CLEANUP=0
    user: root
    volumes:
      - ./config:/home/django/srv/config
      - ./requirements:/home/django/srv/requirements
      - ./sherbet:/home/django/srv/sherbet
  frontend:
    build:
      args:
        - DOCKER_CLEANUP=0
    user: root
