version: '3'

services:
  django: &django
    build:
      context: ./
      dockerfile: ./compose/django/Dockerfile
    command: ./compose/django/start.sh
    image: sherbet_django
    ports:
      - "8000:8000"
