# Generated by Django 3.1.1 on 2021-04-06 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_auto_20200927_1518'),
        ('comments', '0003_auto_20200927_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_family', to='families.family'),
        ),
    ]
