version: '3'

services:
  django: &django
    build:
      context: ../
      dockerfile: ./compose/django/Dockerfile
    command: ./compose/django/start.sh
    image: sherbet_django
    env_file:
      - 'local.env'
    ports:
      - "8000:8000"
  postgres:
    image: postgres
    env_file:
      - 'local.env'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
